### ISSUE TITLE
Bridged network support

### ISSUE THREAD

**Issue by todd-deshane** [kxr/ocp4_setup_upi_kvm#18]
I am looking into a way to get this to work on a bridge networked

For example, I define:

```
<network>
  <name>host-bridge</name>
  <forward mode="bridge"/>
  <bridge name="br1-eno1"/>
</network>
```
The catch is that on this network, I need to hard code the association of the MAC address and the IP address for DHCP to work properly.

I'm trying to decide whether it would be cleaner to specify the mac address with the virt-install steps or to do the initial setup on a private libvirt NAT network and then pivot to the bridged network or would you suggest another alternative?

Thanks for any input. I'm happy to contribute patches to make this easier for those that have a similar bridge network situation.

Also as an aside, it is tricky to get into the guest when it is spinning at "Waiting for loadbalancer VM to obtain an IP address" because the SSH key is not yet in place and the root and core users don't have a password set, so even virsh console is not helpful. Likely there is a trick here too that could be helpful?

**Comment by kxr** [comment]
Hello Todd,
I have seen the request to support bridge/external network, multiple times. And I have thought about trying to support it. The problem is that it gets quite complicated with too many variables/conditions to handle, to the point where its not worth doing it via an automated script. The whole point of this script is to quickly get an OpenShift 4 cluster up and running with least amount of effort possible. The libvirt's NAT network with built-in DHCP and DNS really helps in getting that done without over-complicating things.

If your requirement if for a lab environment, I would highly suggest that you re-consider using the NAT network. It keeps things simple and isolated. And you can easily [expose](https://github.com/kxr/ocp4_setup_upi_kvm#exposing-the-cluster-outside-the-hosthypervisor) the cluster outside the NAT network.

**Comment by todd-deshane** [comment]
The main reason that I wanted to use a bridged network is to add bare metal workers to the cluster. Can this be done with the NAT network?
