### ISSUE TITLE
Unable to add nodes using ./add_node.sh for latest stable release (4.7.13)

### ISSUE THREAD

**Issue by gary-crowe** [kxr/ocp4_setup_upi_kvm#26]
I cannot add nodes using the add_node.sh script after deploying latest stable cluster (4.7.13).  It appears that the script utilises 
```coreos.inst.image_url``` but should use: ```coreos.live.rootfs_url=```

I built my cluster using:
```./ocp4_setup_upi_kvm.sh --ocp-version stable```

Looks like the logic to determine string is present in the install script.  Perhaps it should be extended into the add.node.sh script?

**Comment by kxr** [comment]
@gary-crowe Spot on. You are right. I [updated](https://github.com/kxr/ocp4_setup_upi_kvm/commit/0a801b25ed984c951646c65df5b4dd6e6ed51d54#diff-67d410706f0d4acb80e5516d98303441344048ffb110a7340fdf0ffa12263048R869-R873) my script to handle newer versions of OpenShift that need `coreos.live.rootfs_url` instead of `coreos.inst.image_url`, but forgot to update that in `add_node.sh` script. Thank you for pointing this out. I will fix it.

**Comment by kxr** [comment]
Fixed in [18c1ee0](https://github.com/kxr/ocp4_setup_upi_kvm/commit/18c1ee0df7efef9ad847360457db697b8807fe25)
